export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SINGUP_FAIL';

export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const REMOVE_AUTH_LOADING = 'REMOVE_AUTH_LOADING';

export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';

export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL = 'ACTIVATION_SUCCESS';


export const REFRESH_SUCCESS = 'REFRESH_SUCCESS';
export const REFRESH_FAIL = 'REFRESH_FAIL';

export const LOGOUT = 'LOGOUT';

//galeria get
export const GET_CARPETAS_SUCCESS = 'GET_CARPETAS_SUCCESS';
export const GET_CARPETAS_FAIL = 'GET_CARPETAS_FAIL';

export const EDITAR_PRIVACIDAD_CARPETA_SUCCESS = 'EDITAR_PRIVACIDAD_CARPETA_SUCCESS';
export const EDITAR_PRIVACIDAD_CARPETA_FAIL = 'EDITAR_PRIVACIDAD_CARPETA_FAIL';

export const GET_PRIVACIDAD_CARPETA_SUCCESS = 'GET_PRIVACIDAD_CARPETA_SUCCESS';
export const GET_PRIVACIDAD_CARPETA_FAIL = 'GET_PRIVACIDAD_CARPETA_FAIL';

export const EDITAR_ACCESO_CARPETA_SUCCESS = 'EDITAR_ACCESO_CARPETA_SUCCESS';
export const EDITAR_ACCESO_CARPETA_FAIL = 'EDITAR_ACCESO_CARPETA_FAIL';
 
export const GET_ACCESO_CARPETA_SUCCESS = 'GET_ACCESO_CARPETA_SUCCESS';
export const GET_ACCESO_CARPETA_FAIL = 'GET_ACCESO_CARPETA_FAIL';

export const GET_SUBCARPETAS_SUCCESS = 'GET_SUBCARPETAS_SUCCESS';
export const GET_SUBCARPETAS_FAIL = 'GET_SUBCARPETAS_FAIL';

export const GET_IMAGENES_SUCCESS = 'GET_IMAGENES_SUCCESS';
export const GET_IMAGENES_FAIL = 'GET_IMAGENES_FAIL';

export const GET_VIDEOS_SUCCESS = 'GET_VIDEOS_SUCCESS';
export const GET_VIDEOS_FAIL = 'GET_VIDEOS_FAIL';

export const GET_ARCHIVOS_SUCCESS = 'GET_ARCHIVOS_SUCCESS';
export const GET_ARCHIVOS_FAIL = 'GET_ARCHIVOS_FAIL';



//galeria post
export const POST_CARPETA_SUCCESS = 'POST_CARPETA_SUCCESS';
export const POST_CARPETA_FAIL = 'POST_CARPETA_FAIL';
